In [254]:
import pandas as pd
import os
import csv
from dune_client.client import DuneClient

### Add all Rounds and Seasons membership of delegates

In [255]:
delegates = pd.read_csv("../Data/op_delegates.csv")

In [256]:
delegates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5138 entries, 0 to 5137
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   delegate         5138 non-null   object
 1   voting_power     5138 non-null   float64
 2   ch_member_r2     5138 non-null   int64
 3   ch_member_r3     5138 non-null   int64
 4   ch_member_r4     5138 non-null   int64
 5   ch_member_r5     5138 non-null   int64
 6   ch_member_r6     5138 non-null   int64
 7   ch_member_r7     5138 non-null   int64
 8   gc_member_s3     5138 non-null   int64
 9   gc_member_s4     5138 non-null   int64
 10  gc_member_s5     5138 non-null   int64
 11  gc_member_mm_s5  5138 non-null   int64
 12  sc_member_s5     5138 non-null   int64
 13  coc_member_s5    5138 non-null   int64
 14  dab_member_s5    5138 non-null   int64
 15  gc_member_s6     5138 non-null   int64
 16  gc_member_mm_s6  5138 non-null   int64
 17  sc_member_s6     5138 non-null   int64
 18  coc_member_s6    5138 non-null   int64
 19  dab_member_s6    5138 non-null   int64
 20  gc_member_s7     5138 non-null   int64
 21  gc_member_op_s7  5138 non-null   int64
 22  sc_member_s7     5138 non-null   int64
 23  dab_member_s7    5138 non-null   int64
 24  mmc_member_s7    5138 non-null   int64
dtypes: float64(1), int64(23), object(1)
memory usage: 1003.6+ KB

In [257]:
# Load data from other CSV files (unchanged)
citizens_round2 = pd.read_csv("../Data/RPGF_Rounds_Data/Round 2.csv", encoding='latin1')
citizens_round3 = pd.read_csv("../Data/RPGF_Rounds_Data/Round 3.csv", encoding='latin1')
citizens_round4 = pd.read_csv("../Data/RPGF_Rounds_Data/Round 4.csv", encoding='latin1')
citizens_round5 = pd.read_csv("../Data/RPGF_Rounds_Data/Round 5.csv", encoding='latin1')
citizens_round6 = pd.read_csv("../Data/RPGF_Rounds_Data/Round 6.csv", encoding='latin1')
citizens_round7 = pd.read_csv("../Data/RPGF_Rounds_Data/Round 7.csv", encoding='latin1')

acc = pd.read_csv("../Data/Councils_and_Committees_Data/Anticapture_Commission.csv", encoding='latin1')
grants = pd.read_csv("../Data/Councils_and_Committees_Data/Grants_Council.csv", encoding='latin1')
grants_mm = pd.read_csv("../Data/Councils_and_Committees_Data/Grants_Council_MM.csv", encoding='latin1')
grants_op = pd.read_csv("../Data/Councils_and_Committees_Data/Grants_Council_Operations.csv", encoding='latin1')
dab = pd.read_csv("../Data/Councils_and_Committees_Data/Developer_Advisory_Board.csv", encoding='latin1')
coc = pd.read_csv("../Data/Councils_and_Committees_Data/Code_of_Conduct_Council.csv", encoding='latin1')
mmc = pd.read_csv("../Data/Councils_and_Committees_Data/Milestone_and_Metrics_Council.csv", encoding='latin1')

In [258]:
# Drop rows with null values in the 'address' column for each DataFrame
citizens_round2.dropna(subset=['address'], inplace=True)
citizens_round3.dropna(subset=['address'], inplace=True)
citizens_round4.dropna(subset=['address'], inplace=True)
citizens_round5.dropna(subset=['address'], inplace=True)
citizens_round6.dropna(subset=['address'], inplace=True)

acc.dropna(subset=['address'], inplace=True)
grants.dropna(subset=['address'], inplace=True)
grants_mm.dropna(subset=['address'], inplace=True)
grants_op.dropna(subset=['address'], inplace=True)
dab.dropna(subset=['address'], inplace=True)
coc.dropna(subset=['address'], inplace=True)
mmc.dropna(subset=['address'], inplace=True)

In [259]:
# Filter grants data by season 
grants_season3 = grants[grants['season'] == 3]

grants_season4 = grants[grants['season'] == 4]

acc_season5 = acc[acc['season'] == 5]
grants_season5 = grants[grants['season'] == 5]
grants_mm_season5 = grants_mm[grants_mm['season'] == 5]
dab_season5 = dab[dab["season"] == 5]
coc_season5 = coc[coc["season"] == 5]

acc_season5 = acc[acc['season'] == 6]
grants_season6 = grants[grants['season'] == 6]
grants_mm_season6 = grants_mm[grants_mm['season'] == 6]
dab_season6 = dab[dab["season"] == 6]
coc_season6 = coc[coc["season"] == 6]

acc_season7 = acc[acc['season'] == 7]
grants_season7 = grants[grants['season'] == 7]
grants_op_season7 = grants_op[grants_op['season'] == 7]
dab_season7 = dab[dab["season"] == 7]
mmc_season7 = mmc[mmc["season"] == 7]

In [260]:
# Helper function to add missing members
def add_missing_members(data, new_addresses):
    missing_addresses = set(new_addresses['address'].str.lower()) - set(data['delegate'].str.lower())
    missing_df = pd.DataFrame({
        'delegate': list(missing_addresses),
        'voting_power': 0
    })
    data = pd.concat([data, missing_df], ignore_index=True)
    return data

In [261]:
# Load the daily delegate data
data = pd.read_csv("../Data/op_delegates.csv")

# Add missing delegates from various rounds and councils (unchanged)
data = add_missing_members(data, citizens_round2)
data = add_missing_members(data, citizens_round3)
data = add_missing_members(data, citizens_round4)
data = add_missing_members(data, citizens_round5)
data = add_missing_members(data, citizens_round6)
data = add_missing_members(data, citizens_round7)
data = add_missing_members(data, grants_season3)
data = add_missing_members(data, grants_season4)
data = add_missing_members(data, grants_season5)
data = add_missing_members(data, grants_mm_season5)
data = add_missing_members(data, dab_season5)
data = add_missing_members(data, coc_season5)
data = add_missing_members(data, grants_season6)
data = add_missing_members(data, grants_mm_season6)
data = add_missing_members(data, dab_season6)
data = add_missing_members(data, coc_season6)
data = add_missing_members(data, grants_season7)
data = add_missing_members(data, grants_op_season7)
data = add_missing_members(data, dab_season7)
data = add_missing_members(data, mmc_season7)

# Add the columns
data['ch_member_r2'] = None
data['ch_member_r3'] = None
data['ch_member_r4'] = None
data['ch_member_r5'] = None
data['ch_member_r6'] = None
data['ch_member_r7'] = None

data['gc_member_s3'] = None
data['gc_member_s4'] = None

data['gc_member_s5'] = None
data['gc_member_mm_s5'] = None
data['sc_member_s5'] = None
data['coc_member_s5'] = None
data['dab_member_s5'] = None

data['gc_member_s6'] = None
data['gc_member_mm_s6'] = None
data['sc_member_s6'] = None
data['coc_member_s6'] = None
data['dab_member_s6'] = None

data['gc_member_s7'] = None
data['gc_member_op_s7'] = None
data['sc_member_s7'] = None
data['dab_member_s7'] = None
data['mmc_member_s7'] = None

# Create membership columns for existing delegates only if the round/council is active on the file_date
data['ch_member_r2'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in citizens_round2['address'].str.lower().values else 0)

data['ch_member_r3'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in citizens_round3['address'].str.lower().values else 0)

data['ch_member_r4'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in citizens_round4['address'].str.lower().values else 0)

data['ch_member_r5'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in citizens_round5['address'].str.lower().values else 0)

data['ch_member_r6'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in citizens_round6['address'].str.lower().values else 0)

data['ch_member_r7'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in citizens_round7['address'].str.lower().values else 0)

data['gc_member_s3'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in grants_season3['address'].str.lower().values else 0)

data['gc_member_s4'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in grants_season4['address'].str.lower().values else 0)

data['gc_member_s5'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in grants_season5['address'].str.lower().values else 0)

data['gc_member_mm_s5'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in grants_mm_season5['address'].str.lower().values else 0)

data['dab_member_s5'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in dab_season5['address'].str.lower().values else 0)

data['coc_member_s5'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in coc_season5['address'].str.lower().values else 0)

data['gc_member_s6'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in grants_season6['address'].str.lower().values else 0)

data['gc_member_mm_s6'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in grants_mm_season6['address'].str.lower().values else 0)

data['dab_member_s6'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in dab_season6['address'].str.lower().values else 0)

data['coc_member_s6'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in coc_season6['address'].str.lower().values else 0)

data['gc_member_s7'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in grants_season7['address'].str.lower().values else 0)

data['gc_member_op_s7'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in grants_op_season7['address'].str.lower().values else 0)

data['dab_member_s7'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in dab_season7['address'].str.lower().values else 0)

data['mmc_member_s7'] = data['delegate'].apply(
    lambda x: 1 if x.lower() in mmc_season7['address'].str.lower().values else 0)

pd.set_option('future.no_silent_downcasting', True)
data.fillna(0, inplace=True)

In [262]:
data.columns

Index(['delegate', 'voting_power', 'ch_member_r2', 'ch_member_r3',
       'ch_member_r4', 'ch_member_r5', 'ch_member_r6', 'ch_member_r7',
       'gc_member_s3', 'gc_member_s4', 'gc_member_s5', 'gc_member_mm_s5',
       'sc_member_s5', 'coc_member_s5', 'dab_member_s5', 'gc_member_s6',
       'gc_member_mm_s6', 'sc_member_s6', 'coc_member_s6', 'dab_member_s6',
       'gc_member_s7', 'gc_member_op_s7', 'sc_member_s7', 'dab_member_s7',
       'mmc_member_s7'],
      dtype='object')

In [263]:
data

,delegate,voting_power,ch_member_r2,ch_member_r3,ch_member_r4,ch_member_r5,ch_member_r6,ch_member_r7,gc_member_s3,gc_member_s4,...,gc_member_s6,gc_member_mm_s6,sc_member_s6,coc_member_s6,dab_member_s6,gc_member_s7,gc_member_op_s7,sc_member_s7,dab_member_s7,mmc_member_s7
0,0x2ac5393d1f4be4ef89b45ee2f93d7f20a5cf6d5a,7.025915e+06,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0x06ad892ce23c136bbda3a821570343a2af3e2914,5.930925e+06,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0x1b686ee8e31c5959d9f5bbd8122a58682788eead,5.463669e+06,0,0,0,0,0,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,0xf11b6a8c3cb8bb7dbc1518a613b10ceb0bbfc06b,5.221051e+06,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0xeff8d84e0fd304550da242040ccd45bd44ce71f1,5.004721e+06,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5133,0xe7aa7af667016837733f3ca3809bde04697730ef,0.000000e+00,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5134,0x436c7f148cc5dbc90b5531278c87877bdbd83e27,0.000000e+00,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
5135,0xa8f0048a0d1a04663ca5010d0beac5bcaeea0eef,0.000000e+00,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
5136,0xe2a0464f8ae3bd34b6cb1e578c1110321f491b72,0.000000e+00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
5137,0xd7e7bca98ab9fb25e17ad73429e89a40b55708be,0.000000e+00,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [264]:
output_file_path = os.path.join("../Data", "op_delegates.csv")

data.to_csv(output_file_path, index=False)

print("File updated successfully!")

File updated successfully!

### Add influnce according to the active Seasons and Rounds  membership

In [265]:
data = pd.read_csv("../Data/2025-06-23.csv")

In [266]:
# January 16th, 2025 - July 23rd, 2025
weights = {
    "th_vp": 33.73, 
    "ch_vp_r7": 36.08, 
    "gc_vp_s7": 10.59,
    "gc_vp_op_s7": 0.19, 
    "dab_vp_s7": 3.14,
    "mmc_vp_s7": 2.94
}

In [267]:
cols = ['th_vp', 'ch_vp_r7', 'gc_vp_s7', 'gc_vp_op_s7', 'dab_vp_s7', 'mmc_vp_s7']

In [268]:
data['influence'] = round(sum(data[col] * (weights[col] / 100) for col in cols), 6)

In [269]:
data = data.sort_values(by='voting_power', ascending=False)

In [270]:
data.columns

Index(['delegate', 'voting_power', 'th_vp', 'ch_member_r2', 'ch_vp_r2',
       'ch_member_r3', 'ch_vp_r3', 'ch_member_r4', 'ch_vp_r4', 'ch_member_r5',
       'ch_vp_r5', 'ch_member_r6', 'ch_vp_r6', 'ch_member_r7', 'ch_vp_r7',
       'gc_member_s3', 'gc_vp_s3', 'gc_member_s4', 'gc_vp_s4', 'gc_member_s5',
       'gc_vp_s5', 'gc_member_mm_s5', 'gc_vp_mm_s5', 'sc_member_s5',
       'sc_vp_s5', 'coc_member_s5', 'coc_vp_s5', 'dab_member_s5', 'dab_vp_s5',
       'gc_member_s6', 'gc_vp_s6', 'gc_member_mm_s6', 'gc_vp_mm_s6',
       'sc_member_s6', 'sc_vp_s6', 'coc_member_s6', 'coc_vp_s6',
       'dab_member_s6', 'dab_vp_s6', 'gc_member_s7', 'gc_vp_s7',
       'gc_member_op_s7', 'gc_vp_op_s7', 'sc_member_s7', 'sc_vp_s7',
       'dab_member_s7', 'dab_vp_s7', 'mmc_member_s7', 'mmc_vp_s7',
       'influence'],
      dtype='object')

In [271]:
data = data[['delegate', 'th_vp', 'influence']]
data

                                        delegate     th_vp  influence
0     0x2ac5393d1f4be4ef89b45ee2f93d7f20a5cf6d5a  6.214803   2.096253
1     0x06ad892ce23c136bbda3a821570343a2af3e2914  5.246225   1.769552
2     0x1b686ee8e31c5959d9f5bbd8122a58682788eead  4.832912   1.630141
3     0xf11b6a8c3cb8bb7dbc1518a613b10ceb0bbfc06b  4.618303   1.557754
4     0xeff8d84e0fd304550da242040ccd45bd44ce71f1  4.426947   1.493209
...                                          ...       ...        ...
5037  0x34aa3f359a9d614239015126635ce7732c18fdf3  0.000000   0.371959
5038  0xa2bbe92f4e320185dd42261897464f60c9a05a35  0.000000   0.000000
5039  0xa142ab9eab9264807a41f0e5cbdab877d204e233  0.000000   0.371959
5040  0xa50d0e425461ccab26ef30104cdd879b90db3843  0.000000   0.371959
5041  0xc5cd017ce8efd2fefedf114350657394531477ae  0.000000   0.000000

[5138 rows x 3 columns]

In [272]:
data.to_csv("../Data/influence-2025-06-23.csv", index=False)

### Merge both the files on delegate column and add ENS names

In [273]:
data1 = pd.read_csv("../Data/op_delegates.csv")
data2 = pd.read_csv("../Data/influence-2025-06-23.csv")

In [274]:
data1.columns

Index(['delegate', 'voting_power', 'ch_member_r2', 'ch_member_r3',
       'ch_member_r4', 'ch_member_r5', 'ch_member_r6', 'ch_member_r7',
       'gc_member_s3', 'gc_member_s4', 'gc_member_s5', 'gc_member_mm_s5',
       'sc_member_s5', 'coc_member_s5', 'dab_member_s5', 'gc_member_s6',
       'gc_member_mm_s6', 'sc_member_s6', 'coc_member_s6', 'dab_member_s6',
       'gc_member_s7', 'gc_member_op_s7', 'sc_member_s7', 'dab_member_s7',
       'mmc_member_s7'],
      dtype='object')

In [275]:
data2.columns

Index(['delegate', 'th_vp', 'influence'], dtype='object')

In [276]:
# Get the sets of delegates
delegates_1 = set(data1['delegate'].str.lower())
delegates_2 = set(data2['delegate'].str.lower())

# Find differences
only_in_1 = delegates_1 - delegates_2
only_in_2 = delegates_2 - delegates_1

# Display results
print(f"Number of delegates in file 1: {len(delegates_1)}")
print(f"Number of delegates in file 2: {len(delegates_2)}")
print(f"Number of delegates only in file 1: {len(only_in_1)}")
print(f"Number of delegates only in file 2: {len(only_in_2)}")

if only_in_1:
    print("Delegates only in file 1:")
    print(only_in_1)

if only_in_2:
    print("Delegates only in file 2:")
    print(only_in_2)

if not only_in_1 and not only_in_2:
    print("Both files contain exactly the same delegates.")

Number of delegates in file 1: 5138
Number of delegates in file 2: 5138
Number of delegates only in file 1: 0
Number of delegates only in file 2: 0
Both files contain exactly the same delegates.

### Fetch ENS names of Optimism delegates from Dune

In [277]:
api_key = "WPWyWJJZEPTxvOwQmpcHbfbHoqXHaWxv"  # Replace with your Dune API key
query_id = 5351295  # Replace with your query ID

# Initialize the DuneClient
dune = DuneClient(api_key)

# Function to fetch Dune query results
def fetch_dune_query_results(query_id):
    try:
        query_result = dune.get_latest_result(query_id)
        return query_result.result.rows  # Access the rows in the response
    except Exception as e:
        print(f"Error fetching query results: {e}")
        return None

# Function to write results to CSV
def write_to_csv(data, file_name):
    try:
        with open(file_name, mode='w', newline='', encoding='utf-8') as file:
            writer = csv.writer(file)
            
            if len(data) > 0:
                headers = data[0].keys()  # Get keys from the first row
                writer.writerow(headers)
                
                for row in data:
                    writer.writerow(row.values())
        print(f"Data written to {file_name}")
    except Exception as e:
        print(f"Error writing to CSV: {e}")

# Main code to fetch and save results
if __name__ == "__main__":
    result = fetch_dune_query_results(query_id)
    if result:
        file_name = "../Data/optimism_delegates_ens.csv"
        write_to_csv(result, file_name)

Data written to ../Data/optimism_delegates_ens.csv

In [278]:
op_ens = pd.read_csv("../Data/optimism_delegates_ens.csv")

op_ens['delegate'] = op_ens['delegate'].str.lower()
data2 = pd.merge(data2, op_ens, on='delegate', how='left')

# Merge on 'delegate'
merged_df = pd.merge(data1, data2, on="delegate", how="inner")

# Save the merged dataframe
merged_df.to_csv("../Data/op-delegates-2025-06-23.csv", index=False)